// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 whiteo. All rights reserved.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: l2auth.sql

package db

import (
	"context"
	"net/netip"
	"time"
)

const addIPBan = `-- name: AddIPBan :exec
INSERT INTO l2auth.ip_banned (ip, expiry_date, reason)
VALUES ($1, $2, $3)
ON CONFLICT (ip) DO UPDATE
SET expiry_date = EXCLUDED.expiry_date,
    reason = EXCLUDED.reason
`

type AddIPBanParams struct {
	Ip         netip.Addr
	ExpiryDate time.Time
	Reason     string
}

func (q *Queries) AddIPBan(ctx context.Context, arg AddIPBanParams) error {
	_, err := q.db.Exec(ctx, addIPBan, arg.Ip, arg.ExpiryDate, arg.Reason)
	return err
}

const findAccount = `-- name: FindAccount :one
SELECT a.id           AS id,
       a.name         AS name,
       a.pwd          AS pwd,
       a.access_level AS access_level,
       a.last_server  AS last_server,
       a.banned       AS banned
FROM l2auth.account a
WHERE a.name = lower($1)
LIMIT 1
`

type FindAccountRow struct {
	ID          int64
	Name        string
	Pwd         string
	AccessLevel int32
	LastServer  int32
	Banned      bool
}

func (q *Queries) FindAccount(ctx context.Context, lower string) (FindAccountRow, error) {
	row := q.db.QueryRow(ctx, findAccount, lower)
	var i FindAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pwd,
		&i.AccessLevel,
		&i.LastServer,
		&i.Banned,
	)
	return i, err
}

const getActiveIPBans = `-- name: GetActiveIPBans :many
SELECT ip, expiry_date, reason
FROM l2auth.ip_banned
WHERE expiry_date > now()
`

func (q *Queries) GetActiveIPBans(ctx context.Context) ([]L2authIpBanned, error) {
	rows, err := q.db.Query(ctx, getActiveIPBans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []L2authIpBanned
	for rows.Next() {
		var i L2authIpBanned
		if err := rows.Scan(&i.Ip, &i.ExpiryDate, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isIPBanned = `-- name: IsIPBanned :one
SELECT EXISTS (
    SELECT 1
    FROM l2auth.ip_banned
    WHERE ip = $1 AND expiry_date > now()
)
`

func (q *Queries) IsIPBanned(ctx context.Context, ip netip.Addr) (bool, error) {
	row := q.db.QueryRow(ctx, isIPBanned, ip)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const registerAccount = `-- name: RegisterAccount :one
INSERT INTO l2auth.account (name, pwd, last_ip)
VALUES ($1, $2, $3)
RETURNING id
`

type RegisterAccountParams struct {
	Name   string
	Pwd    string
	LastIp *netip.Addr
}

func (q *Queries) RegisterAccount(ctx context.Context, arg RegisterAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, registerAccount, arg.Name, arg.Pwd, arg.LastIp)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const removeIPBan = `-- name: RemoveIPBan :exec
DELETE FROM l2auth.ip_banned
WHERE ip = $1
`

func (q *Queries) RemoveIPBan(ctx context.Context, ip netip.Addr) error {
	_, err := q.db.Exec(ctx, removeIPBan, ip)
	return err
}

const updateAccountLastIPByName = `-- name: UpdateAccountLastIPByName :exec
UPDATE l2auth.account
SET
    last_ip = $2,
    modify_date = now()
WHERE name = $1
`

type UpdateAccountLastIPByNameParams struct {
	Name   string
	LastIp *netip.Addr
}

func (q *Queries) UpdateAccountLastIPByName(ctx context.Context, arg UpdateAccountLastIPByNameParams) error {
	_, err := q.db.Exec(ctx, updateAccountLastIPByName, arg.Name, arg.LastIp)
	return err
}

const updateAccountLastServer = `-- name: UpdateAccountLastServer :exec
UPDATE l2auth.account
SET
    last_server = $2,
    modify_date = now()
WHERE name = $1
`

type UpdateAccountLastServerParams struct {
	Name       string
	LastServer int32
}

func (q *Queries) UpdateAccountLastServer(ctx context.Context, arg UpdateAccountLastServerParams) error {
	_, err := q.db.Exec(ctx, updateAccountLastServer, arg.Name, arg.LastServer)
	return err
}

const updateAccountPasswordByName = `-- name: UpdateAccountPasswordByName :exec
UPDATE l2auth.account
SET
    pwd = $2,
    modify_date = now()
WHERE name = $1
`

type UpdateAccountPasswordByNameParams struct {
	Name string
	Pwd  string
}

func (q *Queries) UpdateAccountPasswordByName(ctx context.Context, arg UpdateAccountPasswordByNameParams) error {
	_, err := q.db.Exec(ctx, updateAccountPasswordByName, arg.Name, arg.Pwd)
	return err
}
