// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 whiteo. All rights reserved.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"
)

type L2authAccount struct {
	ID           int64
	Name         string
	Pwd          string
	AccessLevel  int32
	LastServer   int32
	Banned       bool
	LastIp       *netip.Addr
	ModifyDate   time.Time
	CreationDate time.Time
}

type L2authIpBanned struct {
	Ip         netip.Addr
	ExpiryDate time.Time
	Reason     string
}
