// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"
)

type L2authAccount struct {
	ID           int64
	Name         string
	Pwd          string
	AccessLevel  int32
	LastServer   int32
	Banned       bool
	LastIp       *netip.Addr
	ModifyDate   time.Time
	CreationDate time.Time
}

type L2authIpBanned struct {
	Ip         netip.Addr
	ExpiryDate time.Time
	Reason     string
}
